language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - nightly

install:
  - pyrus install pear/PHP_CodeSniffer
  - phpenv rehash

script:
  - php phpcs.phar --standard=PSR2 -np --extensions=php .

matrix:
    fast_finish: true
