language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - nightly

install:
  - curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar

script:
  - for f in $(find . -name "*.php"); do php phpcs.phar --standard=PSR2 -n "$f"; done

matrix:
    fast_finish: true
